// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTQ07Doov-eSRnHMOoioo6h2vgBAYDvXY',
    appId: '1:634621795193:web:38896c2959be51e9062da8',
    messagingSenderId: '634621795193',
    projectId: 'agroera-project',
    authDomain: 'agroera-project.firebaseapp.com',
    storageBucket: 'agroera-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXuGDGY--Sn4hcnzKbyD96Gg2uCYkj4-g',
    appId: '1:634621795193:android:79dbcdc17d4a8a6e062da8',
    messagingSenderId: '634621795193',
    projectId: 'agroera-project',
    storageBucket: 'agroera-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcsu-XZu33nGqlVZ-Q2x2JIX4etCm6PCM',
    appId: '1:634621795193:ios:20b6e609420d8292062da8',
    messagingSenderId: '634621795193',
    projectId: 'agroera-project',
    storageBucket: 'agroera-project.appspot.com',
    iosBundleId: 'com.example.agroeraProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcsu-XZu33nGqlVZ-Q2x2JIX4etCm6PCM',
    appId: '1:634621795193:ios:e1559acc4212c1f4062da8',
    messagingSenderId: '634621795193',
    projectId: 'agroera-project',
    storageBucket: 'agroera-project.appspot.com',
    iosBundleId: 'com.example.agroeraProject.RunnerTests',
  );
}
